// packages/types/src/enums/error-code.enum.ts
export enum ErrorCode {
  INVALID_FIELD_LENGTH = "INVALID_FIELD_LENGTH",
  ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND",
  SESSION_FULL = "SESSION_FULL",
  INVALID_EMAIL = "INVALID_EMAIL",
  SESSION_NOT_OPEN = "SESSION_NOT_OPEN",
  INVALID_SLOT_VALUES = "INVALID_SLOT_VALUES",
  INVALID_GEO_COORDINATE = "INVALID_GEO_COORDINATE",
  INVALID_CITY_DISTRICT = "INVALID_CITY_DISTRICT",
  SERVER_ERROR = "SERVER_ERROR",
  REQUEST_VALIDATION_FAILED = "REQUEST_VALIDATION_FAILED",
  MALFORMED_REQUEST_BODY = "MALFORMED_REQUEST_BODY",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
}
