// packages/types/src/enums/error-code.enum.ts
export enum ErrorCode {
  INVALID_FIELD_LENGTH = "INVALID_FIELD_LENGTH",
  ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND",
  SESSION_FULL = "SESSION_FULL",
  INVALID_EMAIL = "INVALID_EMAIL",
  SESSION_NOT_OPEN = "SESSION_NOT_OPEN",
  INVALID_SLOT_VALUES = "INVALID_SLOT_VALUES",
  INVALID_GEO_COORDINATE = "INVALID_GEO_COORDINATE",
  SERVER_ERROR = "SERVER_ERROR"
}
