export enum SessionStatus {
  OPEN = "OPEN",
  FULL = "FULL",
  CANCELLED = "CANCELLED",
}

export enum ShuttleType {
  YONEX_AS30 = "YONEX_AS30",
  YONEX_AS50 = "YONEX_AS50",

  VICTOR_MASTER_ACE = "VICTOR_MASTER_ACE",
  VICTOR_CHAMPION_NO1 = "VICTOR_CHAMPION_NO1",
  VICTOR_GOLD_CHAMPION = "VICTOR_GOLD_CHAMPION",

  RSL_CLASSIC = "RSL_CLASSIC",
  RSL_NO1_TOURNEY = "RSL_NO1_TOURNEY",

  LINING_A_PLUS_300 = "LINING_A_PLUS_300",
  LINING_A_PLUS_600 = "LINING_A_PLUS_600",

  AEROPLANE_EG1130 = "AEROPLANE_EG1130",

  FLEET_CHAMPION = "FLEET_CHAMPION",

  PROTECH_MASTERPIECE = "PROTECH_MASTERPIECE",

  OTHER = "OTHER",
}
